# Generated by Django 5.1.2 on 2024-10-22 21:00
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletters", "0002_newsletter_scheculed_for"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsletter",
            old_name="scheculed_for",
            new_name="scheduled_for",
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="scheduled_for",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
